Assignment2/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::post('user/login', array('as' => 'user.login', 'users' => 'UserController@login')); 
Route::get('user/logout', array('as' => 'user.logout', 'users' => 'UserController@logout'));
Route::resource('user', 'UserController');
Route::resource('comment', 'CommentController');
Route::resource('post', 'PostController');

Route::get('/', array('as'=>'home', 'uses'=> 'UserController@index'));

Assignment2/app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');

	public static $rules = array( 
        'username' => 'required|min:4|unique|email', 
        'password' => 'required|unique',
        'firstName' => 'required|min:4',
        'lastName' => 'required|min:4',
        'dateOfBirth' => 'required|min:6',);
}

Assignment2/app/controllers/UserController.php
<?php

class UserController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('users.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$password = $input['password'];
   		$encrypted = Hash::make($password);
   		$user = new User;
		$user->email = $input['email']; 
		$user->password = $encrypted; 
		$user->save();
		return "user created";
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

	public function login()
	{
		$userdata = array(
		'username' => Input::get('email'),
		'firstName' => Input::get('firstName'),
		'lastName' => Input::get('lastName'),
		'password' => Input::get('password'),
		);
		
		//authenticate
		if (Auth::attempt($userdata)){
			return Redirect::to(URL::previous());
		} else {
			return Redirect::to(URL::previous())->withInput();
		}
	}
	public function logout()
	{
		Auth::logout();
		return Redirect::action('UserController@index');
	}
}

Assignment2/app/views/users/create.blade.php
@extends('layout')

@section('title')
Create
@stop

@section('content')

    {{ Form::open(array('url' => secure_url('user'))) }}
    {{ Form::label('email', 'User Name: ') }}
    {{ Form::text('email') }}
    {{ $errors->first('username') }}
    <p></p>
    {{ Form::label('password', 'Password: ') }} 
    {{ Form::text('password') }}
    {{ $errors->first('password') }}
    <p></p>
    
    {{ Form::submit('Create') }} 
    {{ Form::close() }}


@stop

Assignment2/app/views/users/edit.blade.php
@extends('layout')

@section('title')
Edit
@stop

@section('content')

    <h1>EDIT</h1>
    {{ Form::model($user, array('method' => 'PUT', 'route' => array('user.update', $user->id))) }}
    {{ Form::label('email', 'Username: ') }}
    {{ Form::text('email') }}
    {{ $errors->first('email') }}
    <p></p>
    {{ Form::label('password', 'Password: ') }} 
    {{ Form::text('password') }}
    {{ $errors->first('password') }}
    <p></p>
    {{ Form::submit('Update') }} 
    {{ Form::close() }}


@stop

Assignment2/app/views/users/index.blade.php
@extends('layout')

@section('title')
User
@stop

@section('content')
    <ul>
        @foreach ($users as $user)
        <li> {{ link_to_route('user.show', $user->firstName, $user->lastName, 
        $user->dateOfBirth, $user->dateOfBirth, array($user->id)) }} </li>
        @endforeach
    </ul>
    @foreach($posts as $post)
    <p>Title: {{{ $post->title }}}</p>
    <p>Text: {{{ $post->text }}}</p>
    <p>Name: {{{ $user->firstName }}}{{{ $user->lastName }}}</p>

    <p>{{ link_to_route('post.edit', 'Edit', array($post->id)) }} </p>
    
    ￼{{ Form::open(array('method' => 'DELETE', 'route' => array('post.destroy', $post->id))) }}
    
    {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
    {{ Form::close() }}
    @endforeach
    @foreach($comments as $comment)
    <p>Text: {{{ $comment->text }}}</p>
    <p>Name: {{{ $user->firstName }}}{{{ $user->lastName }}}</p>

    <p>{{ link_to_route('comment.edit', 'Edit', array($comment->id)) }} </p>
    
    ￼{{ Form::open(array('method' => 'DELETE', 'route' => array('comment.destroy', $comment->id))) }}
    
    {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
    {{ Form::close() }}
    @endforeach
    
@stop

Assignment2/app/views/users/show.blade.php
@extends('layout')

@section('title')
Show
@stop

@section('content')

    <h1>User</h1>
    <p>First Name: {{{ $user->firstName }}}</p>
    <p>Last Name: {{{ $user->lastName }}}</p>
 
    <p>{{ link_to_route('user.edit', 'Edit', array($user->id)) }} </p>
    
    ￼{{ Form::open(array('method' => 'DELETE', 'route' => array('user.destroy', $user->id))) }}
    
    {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
    {{ Form::close() }}

@stop